matrix:
  include:
    - language: elixir
      sudo: false
      otp_release:
        - 19.3
      elixir:
        - 1.6
      env:
        global:
          - MIX_ENV=test
      cache:
        directories:
          - _build
          - deps
      script:
        - mix deps.get
        - mix credo --strict
        - mix test
    - language: node_js
      node_js:
        - "10"
      cache:
        directories:
          - "node_modules"
      install:
        - npm install
      script:
        - npm run lint
        - npm run build
